# Example answer file for setup-alpine script
# If you don't want to use a certain option, then comment it out

# Use US layout with US variant
KEYMAPOPTS="us us"

# Set hostname to 'alpine'
HOSTNAMEOPTS=${name}

# Set device manager to mdev
DEVDOPTS=mdev

# Contents of /etc/network/interfaces
INTERFACESOPTS="auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
        address 192.168.5.${ipend}
        broadcast 192.168.5.255
        netmask 255.255.255.0
        gateway 192.168.5.50
        hostname ${name}
        mtu 1400
"

# Search domain of example.com, Google public nameserver
# DNSOPTS="-d example.com 8.8.8.8"
DNSOPTS="8.8.8.8"

# Set timezone to UTC
TIMEZONEOPTS="Europe/Sweden"

# set http/ftp proxy
PROXYOPTS=none

# Add first mirror (CDN)
APKREPOSOPTS="-1"

# Create admin user
#USEROPTS="-a -u -g audio,video,netdev user"
#USERSSHKEY="https://github.com/qzio.keys"
USEROPTS=none

# Install Openssh
SSHDOPTS=openssh
ROOTSSHKEY="https://github.com/qzio.keys"

# Use openntpd
NTPOPTS="openntpd"
#NTPOPTS=none

# Use /dev/sda as a sys disk
#DISKOPTS=none
DISKOPTS="-m sys /dev/vda"

# Setup storage with label APKOVL for config storage
#LBUOPTS="LABEL=APKOVL"
LBUOPTS=none

#APKCACHEOPTS="/media/LABEL=APKOVL/cache"
APKCACHEOPTS=none
